gkpot0 chnget "OparroyAnaloge0"
gkpot1 chnget "OparroyAnaloge1"
gkpot2 chnget "OparroyAnaloge2"
gkpot3 chnget "OparroyAnaloge3"
gkpot4 chnget "OparroyAnaloge4"
gkpot5 chnget "OparroyAnaloge5"
gkpot6 chnget "OparroyAnaloge6"
gkpot7 chnget "OparroyAnaloge7"

gkswitch0 chnget "OparroySwitch0"
gkswitch1 chnget "OparroySwitch1"
gkswitch2 chnget "OparroySwitch2"
gkswitch3 chnget "OparroySwitch3"
gkswitch4 chnget "OparroySwitch4"
gkswitch5 chnget "OparroySwitch5"
gkswitch6 chnget "OparroySwitch6"
gkswitch7 chnget "OparroySwitch7"


gktoggle0 chnget "OparroyToggle0"
gktoggle1 chnget "OparroyToggle1"
gktoggle2 chnget "OparroyToggle2"
gktoggle3 chnget "OparroyToggle3"
gktoggle4 chnget "OparroyToggle4"
gktoggle5 chnget "OparroyToggle5"
gktoggle6 chnget "OparroyToggle6"
gktoggle7 chnget "OparroyToggle7"

gkPWM0 init 0
gkPWM1 init 0
gkPWM2 init 0
gkPWM3 init 0
gkPWM4 init 0
gkPWM5 init 0
gkPWM6 init 0
gkPWM7 init 0

chnset gkPWM0, "OparroyPWM_0"
chnset gkPWM1, "OparroyPWM_1"
chnset gkPWM2, "OparroyPWM_2"
chnset gkPWM3, "OparroyPWM_3"
chnset gkPWM4, "OparroyPWM_4"
chnset gkPWM5, "OparroyPWM_5"
chnset gkPWM6, "OparroyPWM_6"
chnset gkPWM7, "OparroyPWM_7"
