gkswitch0 chnget "M0"
gkswitch1 chnget "M1"
gkswitch2 chnget "M2"
gkswitch3 chnget "M3"
gkswitch4 chnget "M4"
gkswitch5 chnget "M5"
gkswitch6 chnget "M6"
gkswitch7 chnget "M7"

gktoggle0 chnget "T0"
gktoggle1 chnget "T1"
gktoggle2 chnget "T2"
gktoggle3 chnget "T3"
gktoggle4 chnget "T4"
gktoggle5 chnget "T5"
gktoggle6 chnget "T6"
gktoggle7 chnget "T7"

gkled0 init 0
gkled1 init 0
gkled2 init 0
gkled3 init 0
gkled4 init 0
gkled5 init 0
gkled6 init 0
gkled7 init 0

chnset gkled0, "L0"
chnset gkled1, "L1"
chnset gkled2, "L2"
chnset gkled3, "L3"
chnset gkled4, "L4"
chnset gkled5, "L5"
chnset gkled6, "L6"
chnset gkled7, "L7"

