	if (gktoggle0 == 1) then
		gkled0 = 1
	elseif (gktoggle0 == 0) then
		gkled0 = 0
	endif

	if (gktoggle1 == 1) then
		gkled1 = 1
	elseif (gktoggle1 == 0) then
		gkled1 = 0
	endif

	if (gkswitch2 == 1) then
		gkled2 = 1
	elseif (gkswitch2 == 0) then
		gkled2 = 0
	endif

	if (gkswitch3 == 1) then
		gkled3 = 1
	elseif (gkswitch3 == 0) then
		gkled3 = 0
	endif

	if (gkswitch4 == 1) then
		gkled4 = 1
	elseif (gkswitch4 == 0) then
		gkled4 = 0
	endif

	if (gkswitch5 == 1) then
		gkled5 = 1
	elseif (gkswitch5 == 0) then
		gkled5 = 0
	endif

	if (gkswitch6 == 1) then
		gkled6 = 1
	elseif (gkswitch6 == 0) then
		gkled6 = 0
	endif

	if (gkswitch7 == 1) then
		gkled7 = 1
	elseif (gkswitch7 == 0) then
		gkled7 = 0
	endif